fix: exclude supplier sourced items while creating SCR from SCO
MyuddinKhatri/erpnext pull request #6
Opened 2023-06-06 11:31 UTC by MyuddinKhatri

exclude supplier sourced items while creating SCR from SCO
Fetch Supplied items from Subcontracting Order instead of BOM while creating Subcontracting Receipt

2023-06-06 11:37 UTC, Alchez requested changes

2023-06-06 11:37 UTC, Alchez commented on erpnext/controllers/subcontracting_controller.py
> +			frappe.get_all("Subcontracting Order Supplied Item", fields=fields, filters={"parent": sco, "main_item_code":item_code, "sourced_by_supplier": 0}) or []
`frappe.get_all` will return an empty array by default, do we need the `or []` at the end?

2023-06-06 11:37 UTC, Alchez commented on erpnext/controllers/subcontracting_controller.py
> +		fields =  [
```suggestion
		fields = [
```

2023-06-06 11:37 UTC, Alchez commented on erpnext/controllers/subcontracting_controller.py
> +			frappe.get_all("Subcontracting Order Supplied Item", fields=fields, filters={"parent": sco, "main_item_code":item_code, "sourced_by_supplier": 0}) or []
```suggestion
			frappe.get_all("Subcontracting Order Supplied Item", fields=fields, filters={"parent": sco, "main_item_code": item_code, "sourced_by_supplier": 0})
```

2023-06-06 11:37 UTC, Alchez commented on erpnext/controllers/subcontracting_controller.py
> +						qty = flt(sco_supplied_item.qty_consumed_per_unit) * row.conversion_factor
Does this need conversion? Or should it be the same as the SCO table?

2023-06-07 07:51 UTC, MyuddinKhatri commented on erpnext/controllers/subcontracting_controller.py
> +						qty = flt(sco_supplied_item.qty_consumed_per_unit) * row.conversion_factor
It can be same as SCO table

2023-06-07 08:51 UTC, Alchez approved these changes

2023-06-07 08:51 UTC, merged